version: '3.9'

services:
  ## INITIALIZE GENESIS AND SECRETS
  init:
    build:
      context: ../../
      dockerfile: docker/local/Dockerfile
    image: local/go-plgchain
    container_name: go-plgchain-bootstrapper
    command: [ "init", "${EDGE_CONSENSUS:-ibft}" ]
    volumes:
      - data:/data
    networks:
      - go-plgchain-docker

  ## RUN NODES
  node-1:
    image: local/go-plgchain
    container_name: go-plgchain-validator-1
    command: ["server", "--data-dir", "/data/data-1", "--chain", "/data/genesis.json", "--grpc-address", "0.0.0.0:9632", "--libp2p", "0.0.0.0:1478", "--jsonrpc", "0.0.0.0:8545", "--prometheus", "0.0.0.0:5001", "--seal"]
    depends_on:
      init:
        condition: service_completed_successfully
    ports:
      - '10000:9632'
      - '10002:8545'
      - '10003:5001'
    volumes:
      - data:/data
    networks:
      - go-plgchain-docker
    restart: on-failure

  node-2:
    image: local/go-plgchain
    container_name: go-plgchain-validator-2
    command: ["server", "--data-dir", "/data/data-2", "--chain", "/data/genesis.json", "--grpc-address", "0.0.0.0:9632", "--libp2p", "0.0.0.0:1478", "--jsonrpc", "0.0.0.0:8545", "--prometheus", "0.0.0.0:5001", "--seal"]
    depends_on:
      init:
        condition: service_completed_successfully
    ports:
      - '20000:9632'
      - '20002:8545'
      - '20003:5001'
    volumes:
      - data:/data
    networks:
      - go-plgchain-docker
    restart: on-failure

  node-3:
    image: local/go-plgchain
    container_name: go-plgchain-validator-3
    command: ["server", "--data-dir", "/data/data-3", "--chain", "/data/genesis.json", "--grpc-address", "0.0.0.0:9632", "--libp2p", "0.0.0.0:1478", "--jsonrpc", "0.0.0.0:8545", "--prometheus", "0.0.0.0:5001", "--seal"]
    depends_on:
      init:
        condition: service_completed_successfully
    ports:
      - '30000:9632'
      - '30002:8545'
      - '30003:5001'
    volumes:
      - data:/data
    networks:
      - go-plgchain-docker
    restart: on-failure

  node-4:
    image: local/go-plgchain
    container_name: go-plgchain-validator-4
    command: ["server", "--data-dir", "/data/data-4", "--chain", "/data/genesis.json", "--grpc-address", "0.0.0.0:9632", "--libp2p", "0.0.0.0:1478", "--jsonrpc", "0.0.0.0:8545", "--prometheus", "0.0.0.0:5001", "--seal"]
    depends_on:
      init:
        condition: service_completed_successfully
    ports:
      - '40000:9632'
      - '40002:8545'
      - '40003:5001'
    volumes:
      - data:/data
    networks:
      - go-plgchain-docker
    restart: on-failure

networks:
  go-plgchain-docker:
    driver: bridge
    name: go-plgchain-docker

volumes:
  data:
  genesis:
