[profile.default]
src = 'contracts'
test = 'test/forge'
libs = ['node_modules', 'lib']
out = 'out'
cache_path  = 'forge-cache'
remappings = [
  "@utils=test/forge/utils/"
]
verbosity = 2
ffi = true
# comment out if you notice any weird behavior
# sparse_mode = true

# do not use for computationally expensive tests
[profile.intense.fuzz]
runs = 10000

# See more config options https://book.getfoundry.sh/reference/config.html